
services:

  nginx:
    image: nginx
    ports:
     - 80:80
     - 443:443
     - 8888:8888

    container_name: nginx
    volumes:
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d/
      - type: bind
        source: ./cert
        target: /etc/cert

  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    environment:
      - MTX_API=yes
      - MTX_APIADDRESS=:80
      - MTX_AUTHHTTPADDRESS=http://website:8080/auth/rtsp
      - MTX_AUTHMETHOD=http
      - MTX_PATHDEFAULTS_RECORD=yes
      - MTX_PATHDEFAULTS_RECORDDELETEAFTER=1h
      - MTX_PLAYBACK=yes
    ports:
      - 8554:8554
      - 8889:8888
      - 1935:1935
      - 9996:9996
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CHANGE_ME_12345!

  website:
    hostname: SecurityWebsite
    build: ./SecurityWebSite
    container_name: website
    ports:
      - 8080:8080
      - 444:444
    volumes:
      - type: bind
        source: ./cert
        target: /app/cert
      - thumbnails:/app/Thumbnails 
    environment:
      - dbUser=SA
      - dbPassword=CHANGE_ME_12345!
      - dbIP=database

volumes:
  thumbnails:
